name: protee
description: A new Flutter application.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

   # services
  onesignal_flutter: 3.5.0
  device_calendar: ^4.2.0
  shake: ^2.1.0
  clipboard: ^0.1.3

  #firebase
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  firebase_storage: ^11.0.14
  firebase_crashlytics: ^3.0.15
  tab_indicator_styler: ^2.0.0

  #language
  flutter_localizations:
    sdk: flutter
  sprintf: ^7.0.0
  
  #network
  retrofit: ^3.0.1+1
  graphql_flutter: ^5.0.1

  #base
  flutter_native_splash: 2.2.8
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  intl: ^0.17.0
  flutter_svg_provider: ^1.0.3
  flutter_svg: ^1.1.0
  dartx: ^0.7.1
  
  #utils
  flutter_native_timezone: ^2.0.0
  logger: ^1.1.0
  pedantic: ^1.11.1
  date_format: ^2.0.6
  connectivity_plus: ^2.0.3
  package_info: ^2.0.2 
  device_info: ^2.0.2 
  permission_handler: ^9.2.0
  url_launcher: ^6.1.2
  jwt_decode: ^0.3.1
  timeago: ^3.3.0
  geocoding: ^2.0.4
  geolocator: ^9.0.2
  file_picker: ^5.2.5
  image_picker: ^0.8.6+1
  extended_image: ^6.2.1
  image_editor: ^1.3.0
  

  #ui
  cached_network_image: ^3.2.0
  fluttertoast: ^8.0.9
  flutter_statusbarcolor_ns: ^0.4.0
  flutter_spinkit: ^5.1.0
  flutter_easyloading: ^3.0.5
  badges: ^3.0.2
  webview_flutter: ^3.0.4
  pull_to_refresh: ^2.0.0
  rive: ^0.10.3
  modal_bottom_sheet: ^2.1.2
  pull_to_refresh_flutter3: ^2.0.1
  
  #JSON
  json_annotation: ^4.8.0
  phone_numbers_parser: ^7.0.2
  flutter_multi_formatter: ^2.5.1
  expandable: ^5.0.1

  # The easiest way to add facebook login to your flutter app.
  flutter_facebook_auth: ^5.0.8

  #Hive
  hive: ^2.0.4
  hive_flutter: ^1.1.0

  # Sign in
  google_sign_in: ^6.1.0
  google_maps_flutter: 2.2.5

  google_fonts: ^4.0.3

  # Flutter plugin for discovering the state of the soft-keyboard visibility on Android and iOS.
  flutter_keyboard_visibility: ^5.4.1

  # An awesome UI package incluing iOS style cell swipe action effect.You can use this package to implement iOS style tableView cell swipe action
  flutter_swipe_action_cell: ^3.1.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator:  
  build_runner: ^2.0.4 #ns
  retrofit_generator: ^4.0.1
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.10.0
  hive_generator: 2.0.0
  module_generator:
    path: ./tools/module_generator

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/AppIcon-dev.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  macos:
    generate: true
    image_path: "assets/AppIcon-dev.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true 

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/svg/
    - assets/images/png/
    - assets/images/
    - assets/map/
  fonts:
    - family: Nunito
      fonts:
        # Light
        - asset: assets/fonts/Nunito-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        
        # Regular
        - asset: assets/fonts/Nunito-Regular.ttf
          style: normal
          weight: 400

        # MediumBold
        - asset: assets/fonts/Nunito-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          style: italic
          weight: 500

        # SemiBold
        - asset: assets/fonts/Nunito-Semibold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/Nunito-SemiboldItalic.ttf
          style: italic
          weight: 600

        # Bold
        - asset: assets/fonts/Nunito-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          style: italic
          weight: 700

      

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
