import '../../../common/definations.dart';

const otherAssetsRes = '''///This file is automatically generated.
///DO NOT EDIT, all your changes would be lost.
///flutter pub run module_generator:generate_asset [customer, staff]
part of 'assets.dart';

class OtherAssets {
  OtherAssets();$contentKey
}
''';
